#!/usr/bin/env python3

import argparse
import csv
import json
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('input', type=argparse.FileType('r'), nargs='?',
            default=sys.stdin)
    parser.add_argument('-o', dest='output', type=argparse.FileType('w'), nargs='?',
            default=sys.stdout)
    parser.add_argument('--indent', type=int, nargs='?', default=2)
    return parser.parse_args()


def csv2json(input=sys.stdin, output=sys.stdout, **options):
    reader = csv.DictReader(input, delimiter=',')
    rows = list(reader)
    json.dump(rows, output, **options)


def main(**args):
    csv2json(**args)


if __name__ == '__main__':
    args = parse_args()
    main(**vars(args))

