#!/usr/bin/env python3

import argparse
import csv
from functools import reduce
import json
import sys


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('input', type=argparse.FileType('r'), nargs='?',
            default=sys.stdin)
    parser.add_argument('-o', dest='output', type=argparse.FileType('w'), nargs='?',
            default=sys.stdout)
    return parser.parse_args()


def json2csv(input=sys.stdin, output=sys.stdout, **options):
    rows = json.load(input)
    fieldnames = list(reduce(set.union, (set(row.keys()) for row in rows)))
    writer = csv.DictWriter(output, fieldnames)
    writer.writeheader()
    writer.writerows(rows)


def main(**args):
    json2csv(**args)


if __name__ == '__main__':
    args = parse_args()
    main(**vars(args))